### ISSUE TITLE
Value from Trait is serialized twice

### ISSUE THREAD

**Issue by jans23** [FasterXML/jackson-module-scala#207]
I use the following construct with jackson-module-scala 2.5.2 which serializes me the the object RequestSerial("request serial", 10) to

```
{
  "type" : "request serial",
  "type" : "request serial",
  "message_reference" : 10
}
```

while I was expecting

```
{
  "type" : "request serial",
  "message_reference" : 10
}
```

I suspect this is a bug. Please check.

``` scala
object JacksonWrapper {
  val module = new SimpleModule("CustomJson", Version.unknownVersion())

  val mapper = new ObjectMapper() with ScalaObjectMapper
  mapper.registerModule(DefaultScalaModule)
  mapper.registerModule(module)
  mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
  mapper.enable(SerializationFeature.INDENT_OUTPUT); //Enable pretty printing
  mapper.setPropertyNamingStrategy(PropertyNamingStrategy.CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES)

  def serialize(value: Map[Symbol, Any]): String = {
    serialize(value map { case (k,v) => k.name -> v})
  }

  def serialize(value: Any): String =
    mapper.writeValueAsString(value)

  def toMap[V](json:String)(implicit m: Manifest[V]) = deserialize[Map[String,V]](json)

  def deserialize[T](json: String)(implicit m : Manifest[T]): T = {
    mapper.readValue[T](json)
  }
}
```

``` scala
case class RequestSerial(
    `type`: String = "request serial",
    messageReference: Int) extends RequestMessage {

  require(`type` == "request serial", "Parameter 'type' is invalid.")
  require(messageReference > 0, "Empty parameter 'message_reference'.")
}
```

``` scala
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "type")
@JsonSubTypes(Array(
  new Type(value = classOf[RequestSerial], name = "request serial")))
trait RequestMessage {
    val `type`: String
    val messageReference: Int
}
```

Run `println(JacksonWrapper.serialize(RequestSerial("request serial", 10)))` or `JacksonWrapper.deserialize[RequestMessage]("{\"type\":\"request serial\",\"message_reference\":10}")`

**Comment by christophercurrie** [comment]
Sure looks like a bug. I'll take a look and see what I can figure out.

**Comment by cowtowncoder** [comment]
Perhaps this is due to:

https://github.com/FasterXML/jackson-databind/issues/222

**Comment by jans23** [comment]
Hi! I do use EXTERNAL_PROPERTY but don't know if https://github.com/FasterXML/jackson-databind/issues/222 is related or not. Any update from your side?

**Comment by cowtowncoder** [comment]
Looking into this now. One problem I have is regarding precedence: should the value of existing property be used as type id; or should Jackson generate type id using annotation configuration?
Former is actually easier, since then type id serialization could be suppressed, although both could be implemented with some work.

Reading through javadocs for `@JsonTypeInfo` it does read so that if `property` exists, its value would b eused.

**Comment by cowtowncoder** [comment]
For what that's worth, databind#222 is now fixed (for 2.6.0-rc3)

**Comment by jans23** [comment]
Is it suppose to fix this issue? If you provide the RC at mvnnrepo, I would give it a try.

**Comment by cowtowncoder** [comment]
@jans23 Hard to say whether it is the same underlying cause, and Scala runtime has lots of additional logic for property discovery. But there is a good change that could fix this problem.

I will deploy to sonatype snapshot repo now (`jackson-databind`), but one problem is there is not 2.6.0 Release Candidates yet for Scala module. I'll see if @christophercurrie could push 2.6.0-rc2 out.

**Comment by jans23** [comment]
Version 2.6.0-1 does *not* solve the issue for me. Still the same problem.

**Comment by jans23** [comment]
Unfortunately this issue is a show stopper to use Jackson in my case because I couldn't find a workaround. Any news on this issue?

**Comment by christophercurrie** [comment]
I'm able to reproduce the issue, but haven't yet determined a root cause.

**Comment by christophercurrie** [comment]
One thing I do notice, though. You're using `EXTERNAL_PROPERTY`, which is designed to add type information to the serialization that does not exist within the class. What you probably want is `EXISTING_PROPERTY`.

**Comment by jans23** [comment]
I didn't manage to work-around it so it's a big show stopper for me. Any update on this issue?

**Comment by christophercurrie** [comment]
Did you see my note about using `JsonTypeInfo.As.EXISTING_PROPERTY`, instead of `JsonTypeInfo.As.EXTERNAL_PROPERTY`? I suspect that is at least connected to the root cause. I haven't had much time to dig beyond that.

**Comment by jans23** [comment]
I saw your note but I didn't managed to get EXISTING_PROPERTY applied. Also I couldn't find much documentation about it.

**Comment by pjfanning** [comment]
I think it is simply invalid to have a field in the class called 'type' and to have JsonTypeInfo defined with a property called 'type' - this is the reason you get 2 'type's in the serialized json - just use different names for the 2 things - you probably don't even need the 'type' in the case class

**Comment by cowtowncoder** [comment]
By using `EXISTING_PROPERTY` it really should work. Use of `EXTERNAL_PROPERTY` in the original looks off as well.
But the issue is old enough that it is bit hard to reason about it so closing makes sense.

**Comment by pjfanning** [comment]
@cowtowncoder `include = JsonTypeInfo.As.EXISTING_PROPERTY` makes the test case work without having the duplicate `type` fields appear in the serialized json - I've added a test case based on this for regression purposes

**Comment by cowtowncoder** [comment]
Thank you for double-checking @pjfanning !
